-- Create table for daily resort snapshots (history)
create table if not exists resort_snapshots (
  id bigint generated by default as identity primary key,
  resort_id text not null,
  date date not null,
  timestamp timestamptz not null default now(),
  data jsonb not null,
  created_at timestamptz default now()
);

-- Create index for faster querying by resort and date
create index if not exists idx_snapshots_resort_date on resort_snapshots (resort_id, date);

-- Create table for traffic logs
create table if not exists traffic_logs (
  id bigint generated by default as identity primary key,
  city_id text not null,
  city_name text,
  resort_id text not null,
  duration numeric not null,
  delay numeric not null,
  timestamp timestamptz not null default now()
);

-- Create index for faster querying of traffic history
create index if not exists idx_traffic_city_resort on traffic_logs (city_id, resort_id);
create index if not exists idx_traffic_timestamp on traffic_logs (timestamp);
