-- Create table for daily resort snapshots (history)
-- 1. Tables
-- Create table for daily resort snapshots (history)
-- 1. Tables

-- Master table for resort configuration
create table if not exists resorts (
  id text primary key,
  name text not null,
  district text,
  distance integer,
  piste_km numeric,
  lifts integer,
  price numeric,
  classification text,
  website text,
  latitude numeric,
  longitude numeric,
  price_detail jsonb, -- Stores the priceDetail object
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Cities table (Reference data)
create table if not exists cities (
  id text primary key,
  name text not null,
  latitude numeric,
  longitude numeric,
  created_at timestamptz default now()
);

-- Create table for daily resort snapshots (history)
create table if not exists resort_snapshots (
  id bigint generated by default as identity primary key,
  resort_id text not null references resorts(id), -- Added FK
  date date not null,
  timestamp timestamptz not null default now(),
  data jsonb not null,
  created_at timestamptz default now(),
  CONSTRAINT unique_resort_date UNIQUE (resort_id, date)
);

-- Create table for traffic logs
create table if not exists traffic_logs (
  id bigint generated by default as identity primary key,
  city_id text not null references cities(id), -- Added FK
  city_name text,
  resort_id text not null references resorts(id), -- Added FK
  duration numeric not null,
  delay numeric not null,
  timestamp timestamptz not null default now()
);

-- 2. Indexes
create index if not exists idx_snapshots_resort_date on resort_snapshots (resort_id, date);
create index if not exists idx_traffic_city_resort on traffic_logs (city_id, resort_id);
create index if not exists idx_traffic_timestamp on traffic_logs (timestamp);

-- 3. Security (Row Level Security)
-- Enable RLS
ALTER TABLE resort_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE traffic_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE resorts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;

-- Policies
-- 1. Public READ Access (Allowed for everyone)
create policy "Public Read Snapshots" on resort_snapshots for select to anon, authenticated using (true);
create policy "Public Read Traffic" on traffic_logs for select to anon, authenticated using (true);
create policy "Public Read Resorts" on resorts for select to anon, authenticated using (true);
create policy "Public Read Cities" on cities for select to anon, authenticated using (true);

-- 2. Service-Role ONLY WRITE Access
-- (Supabase Service Role bypasses RLS automatically, so we just need to ensure NO policies allow anon writes)
-- Explicitly: No "INSERT/UPDATE/DELETE" policies for anon means they are blocked by default.

-- Create index for faster querying of traffic history
create index if not exists idx_traffic_city_resort on traffic_logs (city_id, resort_id);
create index if not exists idx_traffic_timestamp on traffic_logs (timestamp);

-- ==========================================
-- FUTURE ARCHITECTURE (MDM "Zielbild")
-- ==========================================

-- 1. Master Resort Table (The Brand/Region)
create table if not exists ski_resorts (
    id text primary key,            -- e.g. 'at_tirol_ski_juwel'
    name text not null,
    country_code text not null,     -- 'AT', 'DE'
    region text,                    -- 'Tirol', 'Bayern'
    website text,
    logo_url text,
    created_at timestamptz default now()
);

-- 2. Physical Ski Areas (Child nodes, specific mounts)
create table if not exists ski_areas (
    id text primary key,            -- e.g. 'at_alpbach_wiedersbergerhorn'
    resort_id text references ski_resorts(id),
    name text not null,
    address text,
    latitude numeric,
    longitude numeric,
    elevation_bottom integer,
    elevation_top integer,
    piste_km numeric,
    created_at timestamptz default now()
);

-- 3. Detailed Ticket Prices (History & Variants)
create table if not exists ticket_prices (
    id bigint generated by default as identity primary key,
    resort_id text references ski_resorts(id),
    season_year integer,            -- 2025 (for 25/26)
    season_type text,               -- 'main', 'low', 'pre'
    category text,                  -- 'adult', 'youth', 'child'
    price numeric,
    currency text default 'EUR',
    valid_from date,
    valid_to date,
    created_at timestamptz default now()
);

-- Enable RLS for Future Tables
ALTER TABLE ski_resorts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ski_areas ENABLE ROW LEVEL SECURITY;
ALTER TABLE ticket_prices ENABLE ROW LEVEL SECURITY;

-- Policies (Public Read)
-- Check existence to avoid errors if re-running
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Ski Resorts') THEN
        CREATE POLICY "Public Read Ski Resorts" ON ski_resorts FOR SELECT TO anon USING (true);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Ski Areas') THEN
        CREATE POLICY "Public Read Ski Areas" ON ski_areas FOR SELECT TO anon USING (true);
    END IF;
     IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Ticket Prices') THEN
        CREATE POLICY "Public Read Ticket Prices" ON ticket_prices FOR SELECT TO anon USING (true);
    END IF;
END $$;

-- Recommended Database Optimizations

-- 1. Optimizing Traffic Log Analysis
-- Create a composite index on resort_id and timestamp to speed up trafficAnalysis.js queries
-- which filter by resort_id and range query on timestamp.
CREATE INDEX IF NOT EXISTS idx_traffic_logs_resort_timestamp 
ON traffic_logs (resort_id, timestamp);

-- 2. Ensure resort_id is indexed (usually implicit with foreign key, but good to be explicit for filtering)
CREATE INDEX IF NOT EXISTS idx_traffic_logs_resort_id 
ON traffic_logs (resort_id);

-- 3. Index for timestamp for cleanup jobs (delete old logs)
CREATE INDEX IF NOT EXISTS idx_traffic_logs_timestamp 
ON traffic_logs (timestamp);
