-- Create table for daily resort snapshots (history)
-- 1. Tables
-- Create table for daily resort snapshots (history)
-- 1. Tables

-- Master table for resort configuration
create table if not exists resorts (
  id text primary key,
  name text not null,
  district text,
  distance integer,
  piste_km numeric,
  lifts integer,
  price numeric,
  classification text,
  website text,
  latitude numeric,
  longitude numeric,
  price_detail jsonb, -- Stores the priceDetail object
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Cities table (Reference data)
create table if not exists cities (
  id text primary key,
  name text not null,
  latitude numeric,
  longitude numeric,
  created_at timestamptz default now()
);

-- Create table for daily resort snapshots (history)
create table if not exists resort_snapshots (
  id bigint generated by default as identity primary key,
  resort_id text not null references resorts(id), -- Added FK
  date date not null,
  timestamp timestamptz not null default now(),
  data jsonb not null,
  created_at timestamptz default now(),
  CONSTRAINT unique_resort_date UNIQUE (resort_id, date)
);

-- Create table for traffic logs
create table if not exists traffic_logs (
  id bigint generated by default as identity primary key,
  city_id text not null references cities(id), -- Added FK
  city_name text,
  resort_id text not null references resorts(id), -- Added FK
  duration numeric not null,
  delay numeric not null,
  timestamp timestamptz not null default now()
);

-- 2. Indexes
create index if not exists idx_snapshots_resort_date on resort_snapshots (resort_id, date);
create index if not exists idx_traffic_city_resort on traffic_logs (city_id, resort_id);
create index if not exists idx_traffic_timestamp on traffic_logs (timestamp);

-- 3. Security (Row Level Security)
-- Enable RLS
ALTER TABLE resort_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE traffic_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE resorts ENABLE ROW LEVEL SECURITY;
ALTER TABLE cities ENABLE ROW LEVEL SECURITY;

-- Policies
-- 1. Public READ Access (Allowed for everyone)
create policy "Public Read Snapshots" on resort_snapshots for select to anon, authenticated using (true);
create policy "Public Read Traffic" on traffic_logs for select to anon, authenticated using (true);
create policy "Public Read Resorts" on resorts for select to anon, authenticated using (true);
create policy "Public Read Cities" on cities for select to anon, authenticated using (true);

-- 2. Service-Role ONLY WRITE Access
-- (Supabase Service Role bypasses RLS automatically, so we just need to ensure NO policies allow anon writes)
-- Explicitly: No "INSERT/UPDATE/DELETE" policies for anon means they are blocked by default.

-- Create index for faster querying of traffic history
create index if not exists idx_traffic_city_resort on traffic_logs (city_id, resort_id);
create index if not exists idx_traffic_timestamp on traffic_logs (timestamp);

